### ISSUE TITLE
Cursorless help takes 2-4 seconds to show up

### ISSUE THREAD

**Issue by ParetoOptimalDev** [cursorless-dev/cursorless-talon#156] opened 2022-03-09 22:53 UTC
Context: While reviewing my most frequent commands I noticed i've said 'cursorless help' 52 times this month, then remembered the delay i've been meaning to make an issue for.

Command history shows nearly instantly for comparison. 

I think this might be related to the debounce and multiple draw calls mentioned in #19 .

I'm on NixOS. If no one else is getting this, it could just be because of a different version of QT or an X11 thing.

**Comment by pokey** [comment] 2022-03-09 23:21
Duplicate of https://github.com/cursorless-dev/cursorless-vscode/issues/505

**Closed** 2022-03-09 23:21 UTC
